/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EMAIL_H_RPCGEN
#define _EMAIL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_SR 100
#define MAX_B 240

struct temail {
	double id;
	char sender[MAX_SR];
	char recipient[MAX_SR];
	char subject[MAX_SR];
	char body[MAX_B];
};
typedef struct temail temail;

struct client_name {
	char name[MAX_SR];
};
typedef struct client_name client_name;

struct tinbox {
	struct temail emails[MAX_SR];
	int cont;
};
typedef struct tinbox tinbox;

#define PROG 0x31234567
#define VERSAO 1

#if defined(__STDC__) || defined(__cplusplus)
#define SEND 1
extern  void * send_1(temail *, CLIENT *);
extern  void * send_1_svc(temail *, struct svc_req *);
#define LIST 2
extern  tinbox * list_1(client_name *, CLIENT *);
extern  tinbox * list_1_svc(client_name *, struct svc_req *);
#define DELETE 3
extern  void * delete_1(temail *, CLIENT *);
extern  void * delete_1_svc(temail *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SEND 1
extern  void * send_1();
extern  void * send_1_svc();
#define LIST 2
extern  tinbox * list_1();
extern  tinbox * list_1_svc();
#define DELETE 3
extern  void * delete_1();
extern  void * delete_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_temail (XDR *, temail*);
extern  bool_t xdr_client_name (XDR *, client_name*);
extern  bool_t xdr_tinbox (XDR *, tinbox*);

#else /* K&R C */
extern bool_t xdr_temail ();
extern bool_t xdr_client_name ();
extern bool_t xdr_tinbox ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EMAIL_H_RPCGEN */
