/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "email.h"


void
prog_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	temail  send_1_arg;
	tinbox  *result_2;
	client_name  list_1_arg;
	void  *result_3;
	temail  delete_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = send_1(&send_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = list_1(&list_1_arg, clnt);
	if (result_2 == (tinbox *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = delete_1(&delete_1_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void show_options(int * resp){
    printf("O que deseja fazer?\n");
    printf("1-Enviar\n2-Listar\n");
    scanf("%d", resp);
    setbuf(stdin, NULL);
}

int
main (int argc, char *argv[])
{
	CLIENT *clnt;

	if (argc!=3) {
		fprintf(stderr,"Uso: %s hostname nome",argv[0]);
		exit(0); 
	}
	clnt = clnt_create(argv[1], PROG, VERSAO, "tcp"); 
	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(argv[1]);
		exit(1); 
	}
    int resp;
    show_options(&resp);
    switch (resp)
    {
    case 1:
	    //Passa o nome inserido no terminal como segundo parâmetro de send_message()
        send_message(clnt, strcat(argv[2], "\n")); 
        break;
	case 2:
	    //list_message(clnt, strcat(argv[2], "\n"));
		break;
    default:
        break;
    }
	exit(0);
}
