/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "email.h"

bool_t
xdr_temail (XDR *xdrs, temail *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_long (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->sender, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->recipient, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->subject, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->body, 240,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tinbox (XDR *xdrs, tinbox *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->emails, 100,
		sizeof (temail), (xdrproc_t) xdr_temail))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cont))
		 return FALSE;
	return TRUE;
}
