/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "email.h"
void show(char * str){
	int i;
	printf("Eliminate_enter: %s\n", str);
	for(i=0; i< strlen(str); i++){
		printf("%d - %c\n", i, str[i]);
	}
}

void *
send_1_svc(temail *email, struct svc_req *rqstp)
{
	static char * result;

	FILE * arq;
    char name_file[103];
	time_t timer;
    printf("Enviando email de %s para %s\n", email->sender, email->recipient);
    strcpy(name_file, email->recipient);
    arq = fopen(strcat(name_file, ".txt"), "a"); //Abre arquivo nomeado como name_file.txt(inclui '\n')
    if(arq == NULL){
        printf("ERRO! Arquivo não pode ser aberto.");
    }else{
		fprintf(arq, "%lf %s\n", email->id, email->sender);
        fputs(email->sender, arq);
		fputs("\n", arq);
        fputs(email->subject, arq);
		fputs("\n", arq);
        fputs(email->body, arq);
		fputs("\n", arq);
    }
    fclose(arq);

	return (void *) &result;
}

tinbox *
list_1_svc(client_name * user, struct svc_req *rqstp)
{
	static tinbox  result;
	printf("Hi");
	FILE * arq;
    temail email;
	int cont = 0;
    char aux[6];
    char name_file[103];
    printf("Listando os e-mails de %s!\n", user->name);
	printf("================ Chekcpoint 4 ==============\n");
    strcpy(name_file, user->name);
	printf("================ Chekcpoint 5 ==============\n");
    arq = fopen(strcat(name_file, ".txt"), "r+");
    if(arq == NULL){
        printf("ERRO! Arquivo não pode ser aberto.");
    }else{
		printf("================ Chekcpoint 6 ==============\n");
        while(fscanf(arq,"%lf", &(email.id))>0){
			printf("================ Chekcpoint 7 ==============\n");
			fgets(email.sender, MAX_SR, arq);
			strcpy(email.recipient, user->name);
			fgets(email.sender, MAX_SR, arq);
			fgets(email.subject, MAX_SR, arq);
			fgets(email.body, MAX_B, arq);
			result.emails[cont] = email;
			cont++;
			
	    }
		result.cont = cont;
    }
    fclose(arq);
    printf("Foram encontrados %d emails!\n", result.cont);
	return &result;
}

void *
delete_1_svc(temail *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}
