/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EMAIL_H_RPCGEN
#define _EMAIL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct temail {
	long id;
	char sender[100];
	char recipient[100];
	char subject[100];
	char body[240];
};
typedef struct temail temail;

struct tinbox {
	struct temail emails[100];
	int cont;
};
typedef struct tinbox tinbox;

#define PROG 0x31234567
#define VERSAO 1

#if defined(__STDC__) || defined(__cplusplus)
#define SEND 1
extern  void * send_1(temail *, CLIENT *);
extern  void * send_1_svc(temail *, struct svc_req *);
#define LIST 2
extern  tinbox * list_1(void *, CLIENT *);
extern  tinbox * list_1_svc(void *, struct svc_req *);
#define DELETE 3
extern  void * delete_1(temail *, CLIENT *);
extern  void * delete_1_svc(temail *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SEND 1
extern  void * send_1();
extern  void * send_1_svc();
#define LIST 2
extern  tinbox * list_1();
extern  tinbox * list_1_svc();
#define DELETE 3
extern  void * delete_1();
extern  void * delete_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_temail (XDR *, temail*);
extern  bool_t xdr_tinbox (XDR *, tinbox*);

#else /* K&R C */
extern bool_t xdr_temail ();
extern bool_t xdr_tinbox ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EMAIL_H_RPCGEN */
