package EmailServer;


/**
* EmailServer/EmailInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from email_interface.idl
* Domingo, 21 de Abril de 2019 09h05min28s BRT
*/

public interface EmailInterface extends EmailInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EmailInterface
