package EmailServer;

/**
* EmailServer/EmailInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from email_interface.idl
* Domingo, 21 de Abril de 2019 09h05min28s BRT
*/

public final class EmailInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public EmailServer.EmailInterface value = null;

  public EmailInterfaceHolder ()
  {
  }

  public EmailInterfaceHolder (EmailServer.EmailInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EmailServer.EmailInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EmailServer.EmailInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EmailServer.EmailInterfaceHelper.type ();
  }

}
