package EmailServer;


/**
* EmailServer/EmailInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from email_interface.idl
* Domingo, 21 de Abril de 2019 09h05min28s BRT
*/

abstract public class EmailInterfaceHelper
{
  private static String  _id = "IDL:EmailServer/EmailInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, EmailServer.EmailInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EmailServer.EmailInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EmailServer.EmailInterfaceHelper.id (), "EmailInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EmailServer.EmailInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EmailInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EmailServer.EmailInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EmailServer.EmailInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EmailServer.EmailInterface)
      return (EmailServer.EmailInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EmailServer._EmailInterfaceStub stub = new EmailServer._EmailInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EmailServer.EmailInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EmailServer.EmailInterface)
      return (EmailServer.EmailInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EmailServer._EmailInterfaceStub stub = new EmailServer._EmailInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
