package EmailServer;


/**
* EmailServer/EmailHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from email_interface.idl
* Domingo, 21 de Abril de 2019 09h05min28s BRT
*/

abstract public class EmailHelper
{
  private static String  _id = "IDL:EmailServer/Email:1.0";

  public static void insert (org.omg.CORBA.Any a, EmailServer.Email that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EmailServer.Email extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "sender",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "recipient",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "subject",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "body",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (EmailServer.EmailHelper.id (), "Email", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EmailServer.Email read (org.omg.CORBA.portable.InputStream istream)
  {
    EmailServer.Email value = new EmailServer.Email ();
    value.id = istream.read_long ();
    value.sender = istream.read_string ();
    value.recipient = istream.read_string ();
    value.subject = istream.read_string ();
    value.body = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EmailServer.Email value)
  {
    ostream.write_long (value.id);
    ostream.write_string (value.sender);
    ostream.write_string (value.recipient);
    ostream.write_string (value.subject);
    ostream.write_string (value.body);
  }

}
