package EmailServer;

/**
* EmailServer/EmailHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from email_interface.idl
* Domingo, 21 de Abril de 2019 09h05min28s BRT
*/

public final class EmailHolder implements org.omg.CORBA.portable.Streamable
{
  public EmailServer.Email value = null;

  public EmailHolder ()
  {
  }

  public EmailHolder (EmailServer.Email initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EmailServer.EmailHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EmailServer.EmailHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EmailServer.EmailHelper.type ();
  }

}
