package EmailServer;


/**
* EmailServer/EmailInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from email_interface.idl
* Domingo, 21 de Abril de 2019 09h05min28s BRT
*/

public abstract class EmailInterfacePOA extends org.omg.PortableServer.Servant
 implements EmailServer.EmailInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("send", new java.lang.Integer (0));
    _methods.put ("delete", new java.lang.Integer (1));
    _methods.put ("list", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // EmailServer/EmailInterface/send
       {
         EmailServer.Email email = EmailServer.EmailHelper.read (in);
         this.send (email);
         out = $rh.createReply();
         break;
       }

       case 1:  // EmailServer/EmailInterface/delete
       {
         EmailServer.Email email = EmailServer.EmailHelper.read (in);
         this.delete (email);
         out = $rh.createReply();
         break;
       }

       case 2:  // EmailServer/EmailInterface/list
       {
         String username = in.read_string ();
         EmailServer.Email $result[] = null;
         $result = this.list (username);
         out = $rh.createReply();
         EmailServer.inboxHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EmailServer/EmailInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public EmailInterface _this() 
  {
    return EmailInterfaceHelper.narrow(
    super._this_object());
  }

  public EmailInterface _this(org.omg.CORBA.ORB orb) 
  {
    return EmailInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class EmailInterfacePOA
