package EmailServer;


/**
* EmailServer/inboxHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from email_interface.idl
* Domingo, 21 de Abril de 2019 09h05min28s BRT
*/

public final class inboxHolder implements org.omg.CORBA.portable.Streamable
{
  public EmailServer.Email value[] = null;

  public inboxHolder ()
  {
  }

  public inboxHolder (EmailServer.Email[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EmailServer.inboxHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EmailServer.inboxHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EmailServer.inboxHelper.type ();
  }

}
