package EmailServer;


/**
* EmailServer/inboxHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from email_interface.idl
* Domingo, 21 de Abril de 2019 09h05min28s BRT
*/

abstract public class inboxHelper
{
  private static String  _id = "IDL:EmailServer/inbox:1.0";

  public static void insert (org.omg.CORBA.Any a, EmailServer.Email[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EmailServer.Email[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = EmailServer.EmailHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (EmailServer.inboxHelper.id (), "inbox", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EmailServer.Email[] read (org.omg.CORBA.portable.InputStream istream)
  {
    EmailServer.Email value[] = null;
    int _len0 = istream.read_long ();
    value = new EmailServer.Email[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = EmailServer.EmailHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EmailServer.Email[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      EmailServer.EmailHelper.write (ostream, value[_i0]);
  }

}
