module EmailServer{
    struct Email{
        long id;
        string sender;
        string recipient;
        string subject;
        string body;
    };

    typedef sequence <Email> inbox;

    interface EmailInterface {
        void send(in Email email);
        void delete(in Email email);
        inbox list(in string username);        
    };
};

